import os

def create_project_structure(target_dir: str, project_type: str, project_name: str, force: bool = False) -> dict:
    """
    Creates project directory structure and default source templates according to project type.
    Returns: generated config data dict.
    """
    # Create target directory
    os.makedirs(target_dir, exist_ok=True)

    # Determine folders to create
    if project_type == "executable":
        folders = ["src", "include", "lib", "build"]
    elif project_type in ("static_lib", "shared_lib"):
        folders = ["src", "include", "lib"]
    elif project_type == "cpp_only":
        folders = ["src"]
    else:
        raise ValueError(f"Unknown project type: '{project_type}'")

    for folder in folders:
        os.makedirs(os.path.join(target_dir, folder), exist_ok=True)

    src_dir = os.path.join(target_dir, "src")

    # Generate default source files
    if project_type in ("executable", "cpp_only"):
        main_pengu_path = os.path.join(src_dir, "main.pengu")
        if not os.path.exists(main_pengu_path) or force:
            with open(main_pengu_path, "w", encoding="utf-8") as f:
                f.write(
                    "# main.pengu - Generated by PenguScript CLI\n"
                    "use_cpp <iostream>\n\n"
                    "main = (): int ->\n"
                    "  std.cout << \"Hello from PenguScript!\" << std.endl\n"
                    "  return 0\n"
                )
    elif project_type in ("static_lib", "shared_lib"):
        lib_pengu_path = os.path.join(src_dir, "lib.pengu")
        if not os.path.exists(lib_pengu_path) or force:
            with open(lib_pengu_path, "w", encoding="utf-8") as f:
                f.write(
                    "# lib.pengu - Generated by PenguScript CLI\n"
                    "use_cpp <iostream>\n\n"
                    "# Example library function\n"
                    "add = (a: int, b: int): int ->\n"
                    "  return a + b\n"
                )

    # Build config dictionary
    config_data = {
        "name": project_name,
        "version": "0.1.0",
        "type": project_type,
        "main": "src/main.pengu" if project_type in ("executable", "cpp_only") else "",
        "src_dirs": ["src"],
        "include_dirs": ["include"] if "include" in folders else [],
        "lib_dirs": ["lib"] if "lib" in folders else [],
        "c_flags": [],
        "ld_flags": [],
        "cpp_standard": "c++20",
        "compiler": "auto",
        "dependencies": []
    }

    return config_data
